import {
  doc, title, p, h2, h3, b, i, code, hl, m, callout, ul, ol, todo, quote,
  columns, table, tabs, codeGroup, mathBlock, toggle, hr,
} from "./build";

// Learn guide 2 — every block, shown by example (the page itself is the demo).

export const blocks = {
  en: doc(
    title("Write with blocks"),
    p("Every paragraph, list, table or equation in Folio is a block. Type ", code("/"), " to add one, or use the Markdown shortcuts below. This page is made only of real blocks, so it shows what each one looks like."),
    h2("Text"),
    p("Make text ", b("bold"), ", ", i("italic"), ", ", code("code"), " or ", hl("highlighted", "yellow"), ". Select it and use the toolbar, or the usual shortcuts ", code("Ctrl B"), " and ", code("Ctrl I"), "."),
    table(
      ["Type", "To get"],
      [code("# "), "Heading 1 (## and ### for smaller ones)"],
      [code("- "), "Bulleted list"],
      [code("1. "), "Numbered list"],
      [code("[] "), "To-do"],
      [code("> "), "Quote"],
      [code("```"), "Code block"],
    ),
    h2("Lists"),
    columns(
      [ul("Bulleted lists", "for ideas in any order", "and notes")],
      [ol("Numbered lists", "for steps", "in order")],
      [todo([true, "To-dos"], [true, "you can tick"], [false, "as you go"])],
    ),
    h2("Callouts and quotes"),
    callout("💡", [p("A callout makes a tip, a warning or a key fact stand out. Pick its icon and color.")], "yellow"),
    callout("⚠️", [p("Emptying the trash deletes its pages for good.")], "red"),
    quote(p("Write it down once, so nobody has to ask twice.")),
    h2("Toggles"),
    toggle("Click to open", [p("Toggles hide details until someone needs them: answers, long examples, old notes.")]),
    h2("Columns"),
    columns(
      [h3("Before"), p("Drag a block to the side of another one to put them in columns.")],
      [h3("After"), p("Each column is a stack of blocks of its own, and its width is adjustable.")],
    ),
    h2("Tabs"),
    tabs(
      { label: "Students", content: [p("Course notes, assignments and group work.")] },
      { label: "Teams", content: [p("Wiki, meeting notes and projects.")] },
      { label: "Communities", content: [p("Resources, decisions and showcases.")] },
    ),
    h2("Equations"),
    p("Inline, like ", m("a^2 + b^2 = c^2"), ", or as a block:"),
    mathBlock("x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}"),
    h2("Code"),
    p("One code block, or a code group with one tab per language:"),
    codeGroup(
      { language: "javascript", code: "const total = items.reduce((sum, x) => sum + x.price, 0);" },
      { language: "python", code: "total = sum(item.price for item in items)" },
    ),
    h2("Tables and databases"),
    p("A ", b("table"), " is for a few rows of text. A ", b("database"), " is for records you filter, sort and view as a board, a calendar or a timeline. See the databases guide."),
    hr(),
    callout("⌨️", [p("Hold a block by its handle ", code("⋮⋮"), " on the left to move it, duplicate it or turn it into another block.")], "blue"),
  ),

  fr: doc(
    title("Écrire avec des blocs"),
    p("Chaque paragraphe, liste, tableau ou équation dans Folio est un bloc. Tapez ", code("/"), " pour en ajouter un, ou utilisez les raccourcis Markdown ci-dessous. Cette page n’est faite que de vrais blocs : elle montre à quoi chacun ressemble."),
    h2("Texte"),
    p("Mettez le texte en ", b("gras"), ", en ", i("italique"), ", en ", code("code"), " ou ", hl("surlignez-le", "yellow"), ". Sélectionnez-le et utilisez la barre d’outils, ou les raccourcis habituels ", code("Ctrl B"), " et ", code("Ctrl I"), "."),
    table(
      ["Tapez", "Pour obtenir"],
      [code("# "), "Titre 1 (## et ### pour les plus petits)"],
      [code("- "), "Liste à puces"],
      [code("1. "), "Liste numérotée"],
      [code("[] "), "Case à cocher"],
      [code("> "), "Citation"],
      [code("```"), "Bloc de code"],
    ),
    h2("Listes"),
    columns(
      [ul("Listes à puces", "pour des idées", "et des notes")],
      [ol("Listes numérotées", "pour des étapes", "dans l’ordre")],
      [todo([true, "Cases à cocher"], [true, "à cocher"], [false, "au fur et à mesure"])],
    ),
    h2("Encadrés et citations"),
    callout("💡", [p("Un encadré met en valeur une astuce, un avertissement ou un point clé. Choisissez son icône et sa couleur.")], "yellow"),
    callout("⚠️", [p("Vider la corbeille supprime ses pages définitivement.")], "red"),
    quote(p("Écrivez-le une fois, pour que personne n’ait à redemander.")),
    h2("Blocs repliables"),
    toggle("Cliquez pour ouvrir", [p("Les blocs repliables cachent les détails jusqu’à ce qu’on en ait besoin : réponses, longs exemples, anciennes notes.")]),
    h2("Colonnes"),
    columns(
      [h3("Avant"), p("Glissez un bloc à côté d’un autre pour les mettre en colonnes.")],
      [h3("Après"), p("Chaque colonne a ses propres blocs, et sa largeur se règle.")],
    ),
    h2("Onglets"),
    tabs(
      { label: "Étudiants", content: [p("Notes de cours, devoirs et travaux de groupe.")] },
      { label: "Équipes", content: [p("Wiki, comptes rendus et projets.")] },
      { label: "Communautés", content: [p("Ressources, décisions et vitrines.")] },
    ),
    h2("Équations"),
    p("En ligne, comme ", m("a^2 + b^2 = c^2"), ", ou en bloc :"),
    mathBlock("x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}"),
    h2("Code"),
    p("Un bloc de code, ou un groupe avec un onglet par langage :"),
    codeGroup(
      { language: "javascript", code: "const total = items.reduce((sum, x) => sum + x.price, 0);" },
      { language: "python", code: "total = sum(item.price for item in items)" },
    ),
    h2("Tableaux et bases de données"),
    p("Un ", b("tableau"), " sert pour quelques lignes de texte. Une ", b("base de données"), " sert pour des fiches que l’on filtre, trie et affiche en kanban, calendrier ou chronologie. Voir le guide des bases de données."),
    hr(),
    callout("⌨️", [p("Attrapez un bloc par sa poignée ", code("⋮⋮"), " à gauche pour le déplacer, le dupliquer ou le transformer en un autre bloc.")], "blue"),
  ),
};
